
[package]
name="faultinj"
version="0.1.1"
license = "MIT"
readme = "README.md"

[dependencies]
libc = "*"
lazy_static = "*"
errno = "*"
rand = "*"

[lib]
name="faultinj"
path="src/fault.rs"
crate_type = ["dylib", "rlib", ]
